pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dnn
image: Visual Studio 2017
nuget:
  project_feed: true
  disable_publish_on_pr: true
  
before_build:
- ps: Set-AppveyorBuildVariable -Name 'ProductVersion' -Value '1.8.4'
- ps: Update-AppveyorBuild -Version '$($ProductVersion)-$(APPVEYOR_BUILD_NUMBER)'
build_script:
- ps: .\Build-Release.ps1 $ProductVersion ''
after_buid:
- ps: Push-AppveyorArtifact build\Releases\$env:APPVEYOR_BUILD_VERSION\ClientDependnecy.$env:APPVEYOR_BUILD_VERSION.nupkg
