version: 1.8.4.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dnn
image: Visual Studio 2017
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: .\Build-Release.ps1 $env:APPVEYOR_BUILD_VERSION ''
artifacts:
- path: build\Releases\**\ClientDependnecy.$env:APPVEYOR_BUILD_VERSION.nupkg
  name: NuGet
