pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dnn
image: Visual Studio 2017
nuget:
  project_feed: true
  disable_publish_on_pr: true
  
environment:
  ProductVersion: 1.8.4
  
before_build:
- ps: Update-AppveyorBuild -Version "$env:ProductVersion.$env:APPVEYOR_BUILD_NUMBER"
build_script:
- ps: .\Build-Release.ps1 $env:ProductVersion ''
after_build:
- ps: Push-AppveyorArtifact build\Releases\v$env:ProductVersion\ClientDependnecy.$env:ProductVersion.nupkg
